# basic options
title: Fave Data Team is Hiring
author: Aiyas
email: aiyas@myfave.com
description: Job Scope
twitter_username: ayswl
github_username:  ayswl

# Build settings
markdown: kramdown
theme: jekyll-theme-slate